Chartpage
projectgrotch/project-fe pull request #18
Opened 2019-05-15 16:04 UTC by njblore

2019-05-15 16:12 UTC, olliebs1 requested changes

2019-05-15 16:12 UTC, olliebs1 commented on lib/calendar.dart
> +      margin: EdgeInsets.symmetric(
lines 77  - 92 can be removed

2019-05-15 16:14 UTC, njblore reviewed
done

2019-05-16 07:12 UTC, olliebs1 approved these changes

2019-05-16 07:12 UTC, merged